### PR TITLE
validate format of feedback email, use shared validator

### PR DESCRIPTION
**Pull request by gidsg**
### Context
previously we did not validate format of feedback email address (when populated)

### Changes proposed in this pull request
validate feedback email, use shared custom validator

### Guidance to review
invalid feedback email should report error

### CODE REVIEW

**Comment by edent** [comment]
That's not the right way to validate an email address.

Fails on:
* Unicode TLDs like .中国
* Unicode domains like http://☮.com
* Usernames with apostrophes like `baba.o'riley@example.com`

Succeeds on:
* Domains with invalid characters like `test@exampl_.com`

**Comment by gidsg** [comment]
thanks for your feedback @edent do you know of a regex which matches these cases? Or would you suggest it's not something that can be done in a regex?

**Comment by gidsg** [comment]
@edent ...I have updated it now to use the `email_validator` gem which should support valid email addresses as described in: https://github.com/balexand/email_validator/blob/master/spec/email_validator_spec.rb

**Comment by edent** [comment]
That gem looks long abandoned.  The only true way to validate an email address is to send an email to it.

**Comment by dankmitchell** [comment]
@gidsg maybe we should either use this fork (https://github.com/mailtop/email_validator) or not bother at all.

Verify-frontend is using this gem and I've used it successfully in the past.

**Comment by gidsg** [comment]
@edent re: https://github.com/openregister/registers-frontend/pull/326#issuecomment-393136359 I understand your concern about sending a validation email to the user, however, this is not within the scope of this particular PR. We may consider this as part of future feature development.

**Pull request merged**
