### PR TITLE
Update images on homepage

### PR DESCRIPTION
**Pull request by dankmitchell**
### Changes proposed in this pull request
Update homepage images

### Guidance to review
# After
screen shot 2018-06-04 at 12 59 10

### CODE REVIEW

**Comment by gidsg** [comment]
Is there a reason the images are these dimensions? As they seem to always be being scaled down in the browser.

**Comment by dankmitchell** [comment]
Supplied by @conordelahunty...

**Comment by gidsg** [comment]
I think these should be scaled down to 465x310

**Comment by dankmitchell** [comment]
Done @gidsg. I really think we need SVG's at some stage

**Pull request merged**
